[tool.poetry]
name = "zebra"
version = "0.1.0"
description = "Generator and solver for zebra puzzles"
authors = ["Tushar Chandra <me@tusharc.dev>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
pycosat = "^0.6.3"

[tool.poetry.dev-dependencies]
black = "^19.10b0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
